matrícula = str(input('Digite a sua matrícula: '))
curso = str(input('Digite o curso que você esta fazendo: '))
idade = int(input('Digite a sua idade: '))
print('A sua matrícula é {} \nO curso que você está fazendo é {} \nE você tem {} anos de idade'.format(matrícula,curso,idade))
print('A variável "matrícula" está no endereço',hex(id(matrícula)))
print('A variável "curso" está no endereço',hex(id(curso)))
print('A variável "idade" está no endereço',hex(id(idade)))
print(type(matrícula))
print(type(curso))
print(type(idade))