nome = str(input('Digite o seu Nome: '))
peso = int(input('Digite o seu Peso: '))
idade = int(input('Digite a sua Idade: '))
print('O seu nome e {} é você tem {} anos de idade e o seu peso e de {}'.format(nome,idade,peso))
print('A variável "nome" está no endereço',hex(id(nome)))
print('A variável "idade" está no endereço',hex(id(idade)))
print(type(nome))
print(type(peso))
print(type(idade))
