import math

print('a)45°')
print('Seno: ', math.sin(45))
print('Coseno: ', math.cos(45)) 
print('Tangente: ', math.tan(45)) 
print('Seno em graus: ', math.sin(math.radians(45))) 
print('Coseno em graus: ', math.cos(math.radians(45)))
print('Tangente em graus: ', math.tan(math.radians(45)))
#
print('b)60°')
print('Seno: ', math.sin(60))
print('Coseno: ', math.cos(60)) 
print('Tangente: ', math.tan(60)) 
print('Seno em graus: ', math.sin(math.radians(60))) 
print('Coseno em graus: ', math.cos(math.radians(60)))
print('Tangente em graus: ', math.tan(math.radians(60)))
#
print('c)90°')
print('Seno: ', math.sin(90))
print('Coseno: ', math.cos(90)) 
print('Tangente: ', math.tan(90)) 
print('Seno em graus: ', math.sin(math.radians(90))) 
print('Coseno em graus: ', math.cos(math.radians(90)))
print('Tangente em graus: ', math.tan(math.radians(90)))
#
print('d)180°')
print('Seno: ', math.sin(180))
print('Coseno: ', math.cos(180)) 
print('Tangente: ', math.tan(180)) 
print('Seno em graus: ', math.sin(math.radians(180))) 
print('Coseno em graus: ', math.cos(math.radians(180)))
print('Tangente em graus: ', math.tan(math.radians(180)))
#
print('e)270°')
print('Seno: ', math.sin(270))
print('Coseno: ', math.cos(270)) 
print('Tangente: ', math.tan(270)) 
print('Seno em graus: ', math.sin(math.radians(270))) 
print('Coseno em graus: ', math.cos(math.radians(270)))
print('Tangente em graus: ', math.tan(math.radians(270)))
#
print('f)360°')
print('Seno: ', math.sin(360))
print('Coseno: ', math.cos(360)) 
print('Tangente: ', math.tan(360)) 
print('Seno em graus: ', math.sin(math.radians(360))) 
print('Coseno em graus: ', math.cos(math.radians(360)))
print('Tangente em graus: ', math.tan(math.radians(360)))